#!/bin/bash
# Program:
#  为骑马与砍杀 mod 选择提供界面
# History:
# 2019-02-20 zerolee First release

# 使用：
#      将 ~/公共/game/mbwarband_beta_amd64.appimage 修改为自己的
#      mbwarband_beta_amd64.appimage 存放路径
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

# 初始化相关变量
i=3
mods=(zhantuan napoleonic viking)
modi=(FALSE FALSE FALSE)
modls=`ls -F ~/.mbwarband/|grep \.\*/|egrep -v "(SceneObj|mod|Savegames|Characters/$)"`

for var in $modls
do
    mods[$i]=${var%*/}
    [ -d ~/.mbwarband/Savegames/${var%*/} ] || mkdir  ~/.mbwarband/Savegames/${var%*/}
    modi[$i]=FALSE
    i=$[$i + 1]
done


# 首先判断 last_module_warband 存在不存在，
# 存在则启动此文件中记录的 mod 为默认, 否则战团为默认
if [ -f ~/.mbwarband/last_module_warband ]; then
    lmw=`cat ~/.mbwarband/last_module_warband`
    if [ "$lmw" == "mod" ]; then
        mod=`file ~/.mbwarband/mod`
        k=3
        for var in $modls
        do
            if [ "${mod##*/}" == "${var%*/}" ]; then
                modi[$k]=TRUE
            fi
            k=$[$k + 1]
        done
    elif [ "$lmw" == "Napoleonic Wars" ]; then
        modi[1]=TRUE
    else
        modi[2]=TRUE
    fi
else
    modi[0]=TRUE
fi

# 将 modi 和 mods 进行连接， 为 zenity 的 radiolist 提供值。
for (( j=0; j<i; j=j+1 ))
do
    modz=$modz" "${modi[$j]}" "${mods[$j]}
done

ans=$(zenity  --list  --text "骑马与砍杀 mod 选择" --radiolist  --column "选择" \
              --column "mod" $modz --height=$[200 + 20 * $[$i - 3]] --width=330);

# 用户进行选择，选择战团，则 last_module_warband 文件必须消失
if [ ! -z $ans ]; then
    [ -f ~/.mbwarband/last_module_warband ] && rm ~/.mbwarband/last_module_warband
    [ -e ~/.mbwarband/mod ] && rm -rf ~/.mbwarband/mod
    [ -e ~/.mbwarband/Savegames/mod ] && rm -rf ~/.mbwarband/Savegames/mod
    case $ans in
        "zhantuan")
        ;;
        "napoleonic")
            echo "Napoleonic Wars" >  ~/.mbwarband/last_module_warband
            ;;
        "viking")
            echo "Viking Conquest" >  ~/.mbwarband/last_module_warband
            ;;
        *)
            echo "mod" > ~/.mbwarband/last_module_warband
            ln -s ~/.mbwarband/$ans ~/.mbwarband/mod
            ln -s ~/.mbwarband/Savegames/$ans ~/.mbwarband/Savegames/mod
            ;;
    esac
    ~/公共/game/mbwarband_beta_amd64.appimage
fi
